base_url = 'https://www.numbeo.com/cost-of-living/historical-data-city-selector'

green_shades = [
    "#314026", 
    "#526a40",
    "#739559",
    "#94bf73",
    "#b5ea8c",
    "#daf5c6",
    "#edfae3",
]

orange_shades = [
    "#787878", # Original Orange
    "#e8e8e8",
    "#ecc9a8",
    "#f0a967",
    "#e87f54",
    "#df5441",
    "#363636",
]



countries = ['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 
'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Bermuda', 'Bolivia', 
'Bosnia And Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Cambodia', 'Cameroon', 'Canada', 
'Cayman Islands', 'Chile', 'China', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 
'Czech Republic', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Estonia', 'Ethiopia', 
'Fiji', 'Finland', 'France', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guyana', 'Honduras', 
'Hong Kong (China)', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle Of Man', 
'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 
'Kosovo (Disputed Territory)', 'Kuwait', 'Kyrgyzstan', 'Latvia', 'Lebanon', 'Libya', 'Lithuania', 
'Luxembourg', 'Macao (China)', 'Madagascar', 'Malaysia', 'Maldives', 'Malta', 'Mauritius', 'Mexico', 
'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 
'New Zealand', 'Nicaragua', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama', 
'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russia', 'Rwanda', 
'Saudi Arabia', 'Senegal', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa', 'South Korea', 'Spain', 
'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tanzania', 'Thailand', 
'Trinidad And Tobago', 'Tunisia', 'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 
'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Zambia', 'Zimbabwe']

country_currency = {
    'Afghanistan': '؋',
    'Albania': 'L',
    'Algeria': 'د.ج',
    'Angola': 'Kz',
    'Argentina': '$',
    'Armenia': '֏',
    'Australia': '$',
    'Austria': '€',
    'Azerbaijan': '₼',
    'Bahamas': '$',
    'Bahrain': '.د.ب',
    'Bangladesh': '৳',
    'Barbados': '$',
    'Belarus': 'Br',
    'Belgium': '€',
    'Bermuda': '$',
    'Bolivia': '$b',
    'Bosnia And Herzegovina': 'КМ',
    'Botswana': 'P',
    'Brazil': 'R$',
    'Brunei': '$',
    'Bulgaria': 'лв',
    'Cambodia': '៛',
    'Cameroon': 'FCFA',
    'Canada': '$',
    'Cayman Islands': '$',
    'Chile': '$',
    'China': '¥',
    'Colombia': '$',
    'Costa Rica': '₡',
    'Croatia': 'kn',
    'Cuba': '₱',
    'Curacao': 'ƒ',
    'Cyprus': '€',
    'Czech Republic': 'Kč',
    'Denmark': 'kr',
    'Dominican Republic': 'RD$',
    'Ecuador': '$',
    'Egypt': 'E£',
    'El Salvador': '$',
    'Estonia': '€',
    'Ethiopia': 'Br',
    'Fiji': '$',
    'Finland': '€',
    'France': '€',
    'Georgia': '₾',
    'Germany': '€',
    'Ghana': 'GH₵',
    'Greece': '€',
    'Guatemala': 'Q',
    'Guyana': '$',
    'Honduras': 'L',
    'Hong Kong (China)': 'HK$',
    'Hungary': 'Ft',
    'Iceland': 'kr',
    'India': '₹',
    'Indonesia': 'Rp',
    'Iran': '﷼',
    'Iraq': 'ع.د',
    'Ireland': '€',
    'Isle Of Man': '£',
    'Israel': '₪',
    'Italy': '€',
    'Ivory Coast': 'FCFA',
    'Jamaica': '$',
    'Japan': '¥',
    'Jersey': '£',
    'Jordan': 'د.ا',
    'Kazakhstan': '₸',
    'Kenya': 'KSh',
    'Kosovo (Disputed Territory)': '€',
    'Kuwait': 'د.ك',
    'Kyrgyzstan': 'лв',
    'Latvia': '€',
    'Lebanon': 'ل.ل',
    'Libya': 'ل.د',
    'Lithuania': '€',
    'Luxembourg': '€',
    'Macao (China)': 'P',
    'Madagascar': 'Ar',
    'Malaysia': 'RM',
    'Maldives': 'Rf',
    'Malta': '€',
    'Mauritius': 'Rs',
    'Mexico': '$',
    'Moldova': 'L',
    'Mongolia': '₮',
    'Montenegro': '€',
    'Morocco': 'د.م.',
    'Mozambique': 'MT',
    'Myanmar': 'K',
    'Namibia': 'N$',
    'Nepal': 'रू',
    'Netherlands': '€',
    'New Zealand': '$',
    'Nicaragua': 'C$',
    'Nigeria': '₦',
    'North Macedonia': 'ден',
    'Norway': 'kr',
    'Oman': 'ر.ع.',
    'Pakistan': '₨',
    'Palestine': '₪',
    'Panama': 'B/.',
    'Paraguay': 'Gs',
    'Peru': 'S/.',
    'Philippines': '₱',
    'Poland': 'zł',
    'Portugal': '€',
    'Puerto Rico': '$',
    'Qatar': 'ر.ق',
    'Romania': 'lei',
    'Russia': '₽',
    'Rwanda': 'RF',
    'Saudi Arabia': 'ر.س',
    'Senegal': 'FCFA',
    'Serbia': 'дин',
    'Singapore': '$',
    'Slovakia': '€',
    'Slovenia': '€',
    'South Africa': 'R',
    'South Korea': '₩',
    'Spain': '€',
    'Sri Lanka': 'රු',
    'Sudan': 'SDG',
    'Suriname': '$',
    'Sweden': 'kr',
    'Switzerland': 'CHF',
    'Syria': '£S',
    'Taiwan': 'NT$',
    'Tanzania': 'Sh',
    'Thailand': '฿',
    'Trinidad And Tobago': 'TT$',
    'Tunisia': 'د.ت',
    'Turkey': '₺',
    'Uganda': 'USh',
    'Ukraine': '₴',
    'United Arab Emirates': 'د.إ',
    'United Kingdom': '£',
    'United States': '$',
    'Uruguay': '$U',
    'Uzbekistan': 'лв',
    'Venezuela': 'Bs.',
    'Vietnam': '₫',
    'Zambia': 'ZK',
    'Zimbabwe': 'ZWL'
}


